version: '3.1'

services:
  ym_db_mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - "ym_network"
    volumes:
      - "/db:/db/mongodb/"
    
  ym_db_mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - "ym_network"
    volumes:
      - "/db:/db/mysql/"

networks:
  ym_network:
    external: false
